### ISSUE TITLE
Missing Crucial Files

### ISSUE THREAD

**Issue by DeathlyBower959** [jusoftdev/covid-19-tracker#1]
For your information, you didn't push the package.json file to the GitHub repositiory. This means that people who would like to clone this project, can't run `npm install` as it throws an error.

**Comment by DeathlyBower959** [comment]
You also seem to be missing the utils folder, so you might want to include that in the project

**Comment by juhom205** [comment]
Should be now fixed. Sorry for long response time.
juhom205
